import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage-sec.schoolofpe.inoryasoft.com/oauth/login');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('sp181.1@ino.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('stsamgie');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('heading', { name: 'Holiday Quarter 2024 - FE' }).click();
  await page.getByText('Before you start accessing').click();
  await expect(page.getByText('Before you start accessing')).toBeVisible();
  await page.getByRole('button', { name: 'Get Started' }).click();
  await expect(page.getByText('Have you registered')).toBeVisible();
  await page.getByRole('radio').first().check();
  await page.getByRole('textbox').fill('2025-07-24');
  await page.getByRole('radio').nth(1).check();
  await page.getByRole('combobox').selectOption('30');
  await page.getByRole('combobox').selectOption('30');
  await page.getByRole('combobox').selectOption('30');
  await page.getByRole('button', { name: 'NEXT' }).selectOption('30');
  await page.getByRole('button', { name: 'NEXT' }).selectOption('90');
  await page.getByRole('combobox').click();
  await page.getByRole('combobox').click();
  await page.getByRole('combobox').click();
  await page.getByText('When are you willing to register for the Exam?SelectNext 1 weekNext 2 weeksNext').click();
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('radio').first().check();
  await page.getByRole('radio').nth(1).check();
  await page.locator('div').filter({ hasText: /^Self Study$/ }).getByRole('radio').check();
  await page.getByText('How did you prepare for the last exam?Self StudyGot Course from a training').click();
  await page.getByText('How did you prepare for the last exam?Self StudyGot Course from a training').click();
  await page.getByRole('radio').nth(3).check();
  await page.getByRole('radio').nth(3).check();
  await page.getByRole('textbox').fill('2025-07-25');
  await page.getByRole('button', { name: 'NEXT' }).click();
  await page.getByRole('checkbox', { name: 'Internet Search' }).check();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('Oxford');
  await page.getByText('Finding course/navigationPoorFairGoodVery GoodExcellentInformation on the').click();
  await page.getByRole('img', { name: 'Very Good' }).first().click();
  await page.locator('div').filter({ hasText: /^Puchase\/Enrollment process\?PoorFairGoodVery GoodExcellent$/ }).locator('path').nth(3).click();
  await page.getByRole('textbox', { name: 'Please leave your comments/' }).click();
  await page.getByRole('textbox', { name: 'Please leave your comments/' }).fill('Website is good');
  await page.getByRole('button', { name: 'NEXT' }).click();
});